### ISSUE TITLE
anyone use this code get mAP=27.7 in paper?

### ISSUE THREAD

**Issue by wqingzex** [facebookresearch/video-long-term-feature-banks#15]
I retrain the model with ava dataset, but I get mAP=23.6 with R101-I3D-NL center-crop method, anyone get mAP=27.7

**Comment by chaoyuaw** [comment]
Hi @qingzew , did you train "3D CNN" with R101-I3D-NL backbone (using "ava_r101_baseline") or "LFB-NL-3L" with R101-I3D-NL backbone (using "ava_r101_lfb_nl_3l")? 

If you train "3D CNN" baseline, 23.6 looks reasonable to me. (We got 23.2 in https://github.com/facebookresearch/video-long-term-feature-banks#ava)

**Comment by wqingzex** [comment]
@chaoyuaw yes, I first train ava_r101_baseline/R101-I3D-NL/3D CNN, get mAP=21, then train ava_r101_lfb_nl_3l/R101-I3D-NL/LFB-NL-3L base on the first step, get mAP=23.6(scale=256, center crop)

below is my config:
```
DATASET: ava
DATADIR: data/ava/frames

NUM_GPUS: 1
LOG_PERIOD: 10

MODEL:
  NUM_CLASSES: 80
  MODEL_NAME: resnet_video
  BN_MOMENTUM: 0.9
  BN_EPSILON: 1.0000001e-5
  ALLOW_INPLACE_SUM: True
  ALLOW_INPLACE_RELU: True
  ALLOW_INPLACE_RESHAPE: True
  MEMONGER: True

  BN_INIT_GAMMA: 0.0
  DEPTH: 101
  VIDEO_ARC_CHOICE: 4

  MULTI_LABEL: True
  USE_AFFINE: True

RESNETS:
  NUM_GROUPS: 1  # ResNet: 1x; RESNETS: 32x
  WIDTH_PER_GROUP: 64  # ResNet: 64d; RESNETS: 4d
  TRANS_FUNC: bottleneck_transformation_3d # bottleneck_transformation, basic_transformation

TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 4 #16
  EVAL_PERIOD: 8000
  JITTER_SCALES: [256, 320]

  COMPUTE_PRECISE_BN: False
  CROP_SIZE: 224

  VIDEO_LENGTH: 32
  SAMPLE_RATE: 2
  DROPOUT_RATE: 0.3
  PARAMS_FILE: pretrained_weights/r101_k400_pretrained.pkl
  DATASET_SIZE: 235
  RESET_START_ITER: True

TEST:
  DATA_TYPE: val
  BATCH_SIZE: 4 #16
  CROP_SIZE: 256
  SCALE: 256

  VIDEO_LENGTH: 32
  SAMPLE_RATE: 2

  DATASET_SIZE: 64

SOLVER:
  LR_POLICY: 'steps_with_relative_lrs' # 'step', 'steps_with_lrs', 'steps_with_relative_lrs', 'steps_with_decay'
  BASE_LR: 0.04
  STEP_SIZES: [350000, 50000, 50000]
  #STEP_SIZES: [260000, 20000, 20000]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_ITER: 700000

  WEIGHT_DECAY: 0.000001
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  NESTEROV: True
  SCALE_MOMENTUM: True

  WARMUP:
    WARMUP_ON: True
    WARMUP_START_LR: 0.01
    WARMUP_END_ITER: 2000

CHECKPOINT:
  DIR: '.'
  CHECKPOINT_PERIOD: 4000
  CONVERT_MODEL: True

NONLOCAL:
  USE_ZERO_INIT_CONV: True
  USE_BN: False
  USE_AFFINE: True
  CONV3_NONLOCAL: True
  CONV4_NONLOCAL: True
  USE_SCALE: True

AVA:
  ANNOTATION_DIR: data/ava/annotations
  DETECTION_SCORE_THRESH_TRAIN: 0.9
  DETECTION_SCORE_THRESH_EVAL: [0.85]
  LFB_DETECTION_SCORE_THRESH: 0.9
  TEST_MULTI_CROP: False
  TEST_MULTI_CROP_SCALES: [224, 256, 320]
```
I modify gpu num and max steps, and I am testing multi crop.

I also think there is a bug in queue operator, every time I create train network or test network, some queues will be created, but in multi crop testing, because main thread do not terminate, all the useless queues are still there, so it turns out that out of memory
